services:
  postgres:
    image: 'postgres:latest'
    environment:
      - 'POSTGRES_DB=mydatabase'
      - 'POSTGRES_PASSWORD=itsasecret'
      - 'POSTGRES_USER=tymko'
    ports:
      - '5432:5432'
    volumes:
    - postgres_data:/var/lib/postgresql/main

volumes:
  postgres_data:
    driver: local